# Generated by Django 4.0.5 on 2023-06-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.TextField(default='Image not found')),
                ('location', models.TextField(default=None)),
                ('likes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apiapp.dog')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apiapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apiapp.user'),
        ),
    ]
