# Generated by Django 4.0.5 on 2022-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_dog_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.TextField(default=None),
        ),
    ]
