# Generated by Django 4.0.5 on 2022-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_dog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
