# Generated by Django 4.0.5 on 2022-06-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_alter_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='Image not found', null=True, upload_to='images/'),
        ),
    ]
