# Generated by Django 4.0.5 on 2023-04-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_user_dog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apiapp.dog')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='apiapp.user')),
            ],
        ),
    ]
